---
apiVersion: extensions/v1beta1
kind: Deployment
spec:
  replicas: 4
  template:
    metadata:
      labels:
        networkservicemesh.io/app: "icmp-responder-nsc"
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      containers:
        - name: alpine-img
          image: alpine:latest
          command: ['tail', '-f', '/dev/null']
      initContainers:
        - name: nsc
          image: networkservicemesh/nsc:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: NETWORK_SERVICES
              value: "nsm1:icmp-responder"
          resources:
            limits:
              nsm.ligato.io/socket: 1
metadata:
  name: nsc
  namespace: default
