---
apiVersion: extensions/v1beta1
kind: DaemonSet
spec:
  template:
    metadata:
      labels:
        app: nsm-vpp-dataplane
    spec:
      hostPID: true
      containers:
        - name: vppagent-dataplane
          securityContext:
            privileged: true
          image: networkservicemesh/vppagent-dataplane:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: NSM_DATAPLANE_SRC_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: workspace
              mountPath: /var/lib/networkservicemesh/
              mountPropagation: Bidirectional
      volumes:
        - hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate
          name: workspace
metadata:
  name: nsm-vppagent-dataplane
  namespace: default
